### PR TITLE
Clear search tracks screen after exiting

### LINKED ISSUE #229: After creating a room tracks search engine is not reset
To reproduce the bug
Create a room then leave the room and go back on the bottom bar Search tab. The user is not able to enter any new track than the previous one used to create the room

### PR DESCRIPTION
**Pull request by Devessier**
Closes #229

### CODE REVIEW

File: packages/client/machines/searchTrackMachine.ts [hunk 1]
```diff
@@ -27,45 +31,65 @@ export const searchTrackMachine = searchTrackModel.createMachine(
...
 
-            fetchedTracks: {
-                entry: ['navigateToResultsPage'],
+                on: {
+                    RESET: {
+                        target: 'steps.idle',
+
+                        actions: [
+                            forwardTo('searchBarMachine'),
+                            log('forward RESET event to searchBarMachine'),
```
Comment (prastoin) [inline packages/client/machines/searchTrackMachine.ts:80]: Should this be removed ?

**Review by prastoin — APPROVED** [review]
Great refactor and fix
ready to merge again
